"use client"

import { useState, useEffect } from "react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader } from "@/components/ui/card"
import { Sparkles, Star, Calendar } from "lucide-react"
import { ShareModal } from "./share-modal"
import { getCurrentUser } from "@/lib/auth"

interface ReportDisplayProps {
  report: string
}

export function ReportDisplay({ report }: ReportDisplayProps) {
  const [showShareModal, setShowShareModal] = useState(false)
  const [user, setUser] = useState<any>(null)

  // Check user status when component mounts
  useEffect(() => {
    checkUser()
  }, [])

  const checkUser = async () => {
    const currentUser = await getCurrentUser()
    setUser(currentUser)
  }

  const handleSubscribe = () => {
    // Scroll to pricing section on the main page
    if (window.location.pathname !== "/") {
      window.location.href = "/#pricing"
    } else {
      const pricingSection = document.getElementById("pricing")
      if (pricingSection) {
        pricingSection.scrollIntoView({ behavior: "smooth" })
        // Add visual emphasis
        pricingSection.classList.add("ring-4", "ring-purple-400", "ring-opacity-50")
        setTimeout(() => {
          pricingSection.classList.remove("ring-4", "ring-purple-400", "ring-opacity-50")
        }, 3000)
      }
    }
  }

  const handleGetDailyInsights = () => {
    window.location.href = "/dashboard?tab=daily-insights"
  }

  return (
    <>
      <section className="px-6 py-16 max-w-4xl mx-auto">
        <div className="text-center mb-8">
          <h2 className="text-4xl font-bold text-white mb-4">Your Personal Cosmic Analysis</h2>
          <p className="text-gray-300 text-lg">Generated by KIRA AI using your natal chart and palm analysis</p>
        </div>

        <Card className="bg-white/10 backdrop-blur-md border-white/20 mb-8 relative">
          <CardHeader className="relative">
            <div className="flex items-center justify-between">
              <div className="flex items-center space-x-2">
                <div className="text-2xl font-bold bg-gradient-to-r from-purple-400 to-blue-400 bg-clip-text text-transparent">
                  KIRA
                </div>
                <Star className="w-5 h-5 text-yellow-400" />
              </div>

              {/* Share Button - Top Right */}
              <Button
                onClick={() => setShowShareModal(true)}
                variant="outline"
                size="sm"
                className="border-purple-400/50 bg-purple-500/20 text-white hover:bg-purple-500/30 flex items-center space-x-2"
              >
                <span className="text-lg">📤</span>
                <span className="hidden sm:inline">Share</span>
              </Button>
            </div>
          </CardHeader>

          <CardContent className="p-4 sm:p-8">
            <div className="prose prose-invert max-w-none">
              {report.split("\n\n").map((paragraph, index) => (
                <div key={index} className="mb-4">
                  {paragraph.startsWith("**") ? (
                    <h3 className="text-lg sm:text-xl font-semibold text-purple-300 mb-2">
                      {paragraph.replace(/\*\*/g, "")}
                    </h3>
                  ) : (
                    <p className="text-gray-200 leading-relaxed text-sm sm:text-base">{paragraph}</p>
                  )}
                </div>
              ))}
            </div>
          </CardContent>
        </Card>

        <div className="text-center space-y-6">
          {/* Get My Daily Insights Button - Only show if user is logged in */}
          {user && (
            <div className="mb-6">
              <Button
                onClick={handleGetDailyInsights}
                className="bg-gradient-to-r from-green-500 to-teal-500 hover:from-green-600 hover:to-teal-600 text-white px-8 py-4 text-lg font-semibold mb-4"
              >
                <Calendar className="w-5 h-5 mr-2" />
                Get My Daily Insights
              </Button>
              <p className="text-gray-400 text-sm">Access your personalized daily cosmic guidance</p>
            </div>
          )}

          <div className="flex items-center justify-center space-x-2 text-purple-300 mb-4">
            <Sparkles className="w-5 h-5" />
            <span className="text-lg">Want daily insights like this?</span>
            <Sparkles className="w-5 h-5" />
          </div>

          <Button
            onClick={handleSubscribe}
            className="bg-gradient-to-r from-purple-500 to-blue-500 hover:from-purple-600 hover:to-blue-600 text-white px-8 py-4 text-lg font-semibold"
          >
            Subscribe for Daily Insights
          </Button>

          <div className="text-gray-400 text-sm">Choose your plan below ↓</div>
        </div>
      </section>

      <ShareModal isOpen={showShareModal} onClose={() => setShowShareModal(false)} report={report} />
    </>
  )
}
